// ---------------------------------------------------------------------------
// STRINGS — All user-facing copy in English + Arabic.
// App holds `lang` ('en' | 'ar'), picks STRINGS[lang], and passes `str` down.
// RTL is flipped via dir= on the root element in App.
// ---------------------------------------------------------------------------

const en = {
  dir: 'ltr',
  langName: 'عربي',
  heroTitle: 'What do you feel like watching tonight?',
  heroSub: 'Describe it in your own words — the AI picks real films for exactly that feeling.',
  searchPlaceholder: 'e.g. "stressed about work" or "want to cry"',
  find: 'Find movies',
  reading: 'Reading…',
  examples: [
    'I need a good cry',
    'something cozy for tonight',
    'give me an adrenaline rush',
    'bend my mind',
  ],
  surprise: 'Surprise me',
  share: 'Share these picks',
  copied: 'Link copied!',
  recent: 'Recent',
  aiDown: 'The AI is unavailable right now — try Surprise me.',
  searchHiccup: 'Search hiccup — try again.',
  apiWarnTitle: '⚡ Almost there!',
  apiWarnBody: 'Add your free TMDB API key to get real movies.',
  signIn: 'Sign In',
  signUp: 'Sign Up',
  favTitle: 'Your favorites',
  themeToggleLabel: 'Toggle light and dark mode',
  homeTitle: 'Back to main menu',
  favEmpty: 'No favorites yet — tap the heart on any movie.',
  favSyncIn: 'Synced to your account',
  favSyncOut: 'Sign in to sync favorites on every device',
  closeFavorites: 'Close favorites',
  removeFavorite: (name) => `Remove ${name} from favorites`,
  viewDetailsFor: (name) => `View details for ${name}`,
  favSave: (name) => `Save ${name} to favorites`,
  favRemove: (name) => `Remove ${name} from favorites`,
  excludeSeen: (name) => `Already seen ${name} — exclude it`,
  excludeTitle: 'Already seen this — exclude it',
  noPoster: 'No poster',
  noDescription: 'No description available.',
  yourFavorites: (n) => `♥ Your favorites (${n})`,
  excludedReset: (n) => `${n} excluded — reset`,
  gridEmpty: 'Nothing to show — try a different search, or reset your exclusions above.',
  gridErrorTitle: '😕 Something went wrong',
  tmdbKeyHint: 'Make sure your TMDB API key is set in the .env file',
  badgeAi: 'AI picks',
  badgeLive: 'Live picks',
  surpriseHeading: 'Surprise picks — random treasures, no input required.',
  detailsLoading: 'Loading details…',
  detailsError: (e) => `Couldn't load full details (${e}) — showing basic info.`,
  backToPicks: '← Back to picks',
  topCast: 'Top cast',
  moreLikeThis: 'More like this',
  whereToWatch: 'Where to watch',
  watchSave: (name) => `Save ${name} to watch later`,
  watchRemove: (name) => `Remove ${name} from watch later`,
  watchLaterBtn: '＋ Watch later',
  inWatchlist: '✓ In watchlist',
  favTab: 'Favorites',
  watchTab: 'Watch later',
  trendingTitle: 'Trending this week',
  moviesTab: 'Movies',
  tvTab: 'TV Shows',
  seasons: 'seasons',
  yourRating: 'Your rating',
  forYouTitle: 'For you',
  forYouSub: 'Because of your hearts and watchlist',
  eraAny: 'Any era',
  eraClassic: 'Classics (–1999)',
  eraModern: 'Modern (2000–2015)',
  eraRecent: 'Recent (2016+)',
  minRating: 'Rating',
  anyRating: 'Any',
  familyOnly: 'Family',
  resetFilters: 'Reset',
  statsSeen: 'seen',
  profileTitle: 'Profile',
  tabLibrary: 'Library',
  tabRatings: 'Ratings',
  tabInsights: 'Insights',
  seenSection: 'Seen',
  removeSelected: 'Remove selected',
  clearAll: 'Clear all',
  selectAll: 'Select all',
  emptyShelf: 'Nothing here yet — heart, bookmark, rate, or exclude movies to fill your shelves.',
  yourReview: 'Your review…',
  saveReview: 'Save',
  reviewSaved: 'Saved ✓',
  avgRating: 'Average rating',
  topGenres: 'Top genres',
  totalSearches: 'Searches',
  totalSeen: 'Seen',
  backHome: 'Home',
  guestLibraryNote: 'Guest shelf — sign in to sync it on every device.',
  backToResults: 'Back to results',
  playTrailer: (name) => `Play ${name} trailer`,
  trailerOf: (name) => `${name} trailer`,
  footerPowered: 'Powered by',
  footerNote: '. This product uses the TMDB API but is not endorsed or certified by TMDB.',
};

const ar = {
  ...en,
  dir: 'rtl',
  langName: 'EN',
  heroTitle: 'ماذا تشاهد الليلة؟',
  heroSub: 'صِف شعورك بكلماتك — الذكاء الاصطناعي يختار أفلامًا حقيقية لهذا الشعور.',
  searchPlaceholder: 'مثال: "متوتر بسبب العمل" أو "أريد أن أبكي"',
  find: 'اعثر على أفلام',
  reading: 'يقرأ…',
  examples: [
    'أحتاج أن أبكي',
    'شيء مريح لهذه الليلة',
    'أريد جرعة أدرينالين',
    'فيلم يدوّخ العقل',
  ],
  surprise: 'فاجئني',
  share: 'شارك الاختيارات',
  copied: 'تم نسخ الرابط!',
  recent: 'الأخيرة',
  aiDown: 'الذكاء الاصطناعي غير متاح الآن — جرّب فاجئني.',
  searchHiccup: 'تعذّر البحث — حاول مجددًا.',
  apiWarnTitle: '⚡ خطوة واحدة!',
  apiWarnBody: 'أضف مفتاح TMDB المجاني للحصول على أفلام حقيقية.',
  signIn: 'تسجيل الدخول',
  signUp: 'حساب جديد',
  favTitle: 'المفضلة',
  themeToggleLabel: 'التبديل بين الوضع الفاتح والداكن',
  homeTitle: 'عودة إلى القائمة الرئيسية',
  favEmpty: 'لا مفضلات بعد — اضغط القلب على أي فيلم.',
  favSyncIn: 'تتم المزامنة مع حسابك',
  favSyncOut: 'سجّل الدخول للمزامنة على كل الأجهزة',
  closeFavorites: 'إغلاق المفضلة',
  removeFavorite: (name) => `إزالة ${name} من المفضلة`,
  viewDetailsFor: (name) => `عرض تفاصيل ${name}`,
  favSave: (name) => `حفظ ${name} في المفضلة`,
  favRemove: (name) => `إزالة ${name} من المفضلة`,
  excludeSeen: (name) => `شوهد بالفعل ${name} — استبعاد`,
  excludeTitle: 'شوهد من قبل — استبعاد',
  noPoster: 'لا ملصق',
  noDescription: 'لا يوجد وصف.',
  yourFavorites: (n) => `♥ مفضلاتك (${n})`,
  excludedReset: (n) => `${n} مستبعد — إعادة تعيين`,
  gridEmpty: 'لا شيء للعرض — جرّب بحثًا مختلفًا.',
  gridErrorTitle: '😕 حدث خطأ ما',
  tmdbKeyHint: 'تأكد من وضع مفتاح TMDB في ملف .env',
  badgeAi: 'اختيارات الذكاء الاصطناعي',
  badgeLive: 'اختيارات مباشرة',
  surpriseHeading: 'اختيارات مفاجئة — كنوز عشوائية بدون إدخال.',
  detailsLoading: 'جارٍ تحميل التفاصيل…',
  detailsError: (e) => `تعذّر تحميل التفاصيل الكاملة (${e}) — عرض المعلومات الأساسية.`,
  backToPicks: 'عودة إلى الاختيارات ←',
  topCast: 'طاقم التمثيل',
  moreLikeThis: 'المزيد مثل هذا',
  whereToWatch: 'أين تشاهد',
  watchSave: (name) => `حفظ ${name} للمشاهدة لاحقًا`,
  watchRemove: (name) => `إزالة ${name} من المشاهدة لاحقًا`,
  watchLaterBtn: '＋ مشاهدة لاحقًا',
  inWatchlist: '✓ في قائمة المشاهدة',
  favTab: 'المفضلة',
  watchTab: 'مشاهدة لاحقًا',
  trendingTitle: 'الأكثر رواجًا هذا الأسبوع',
  moviesTab: 'أفلام',
  tvTab: 'مسلسلات',
  seasons: 'مواسم',
  yourRating: 'تقييمك',
  forYouTitle: 'لك',
  forYouSub: 'بناءً على مفضلاتك وقائمتك',
  eraAny: 'أي حقبة',
  eraClassic: 'كلاسيك (–1999)',
  eraModern: 'حديث (2000–2015)',
  eraRecent: 'جديد (2016+)',
  minRating: 'التقييم',
  anyRating: 'الكل',
  familyOnly: 'عائلي',
  resetFilters: 'إعادة تعيين',
  statsSeen: 'شوهد',
  profileTitle: 'الملف',
  tabLibrary: 'المكتبة',
  tabRatings: 'التقييمات',
  tabInsights: 'نظرة',
  seenSection: 'شوهد',
  removeSelected: 'إزالة المحدد',
  clearAll: 'مسح الكل',
  selectAll: 'تحديد الكل',
  emptyShelf: 'لا شيء بعد — اضغط القلب أو الحفظ أو التقييم لملء رفوفك.',
  yourReview: 'مراجعتك…',
  saveReview: 'حفظ',
  reviewSaved: 'تم الحفظ ✓',
  avgRating: 'متوسط التقييم',
  topGenres: 'أكثر الأنواع',
  totalSearches: 'عمليات البحث',
  totalSeen: 'شوهد',
  backHome: 'الرئيسية',
  guestLibraryNote: 'رف الضيف — سجّل الدخول للمزامنة على كل الأجهزة.',
  backToResults: 'عودة إلى النتائج',
  playTrailer: (name) => `تشغيل إعلان ${name}`,
  trailerOf: (name) => `إعلان ${name}`,
  footerPowered: 'مدعوم من',
  footerNote: '. هذا المنتج يستخدم TMDB API وغير معتمد من TMDB.',
};

export const STRINGS = { en, ar };
export const LANGS = ['en', 'ar'];
